name: Bug report
description: Create a report to help us fix something that isn't working as expected
labels: "bug :bug:"
body:
 - type: markdown
   attributes: 
    value: |
    🚨 PLEASE DO NOT SKIP ANY INSTRUCTIONS AND INFORMATION MENTIONED BELOW AS THEY ARE ALL REQUIRED AND ESSENTIAL TO INVESTIGATE THE ISSUE. ISSUES WITH MISSING INFORMATION MAY BE CLOSED WITHOUT INVESTIGATION
    IF YOU'RE NOT CERTAIN ABOUT THE ISSUE AND REQUIRE MORE CLARITY, PLEASE POST ON "QUESTIONS & HELP" CATEGORY OF THE DISCUSSIONS PLATFORM [https://github.com/CommunityToolkit/WindowsCommunityToolkit/discussions/categories/questions-help] WHERE YOU CAN DISCUSS AND ENGAGE WITH THE COMMUNITY TO GAIN FURTHER CLARITY REGARDING THE ISSUE  🚨
 - type: textarea
   id: description
   attributes:
     label: Describe the bug
     description: A clear and concise description of what the bug is.
 - type: checkboxes
   id: is-regression
   attributes:
     description: 
     options:
       - label: This bug is a regression
         required: false
  - type: input
    id: last-working-toolkit-version
    attributes:
      description: If this is a regression, what toolkit version did you last see it work?
      placeholder: 
    validations:
      required: false
 - type: checkboxes
   id: reproducable-in-sample-app
   attributes: 
     description: Can this be reproduced in the Sample App? (Either in a sample as-is or with new XAML pasted in the editor.) Being able to reproduce the problem in the sample app, really stream-lines the whole process in being able to discover, resolve, and validate bug fixes.
     options:
       - label: This bug can be reproduced in the sample app.
         required: false
   validations:
     required: false
 - type: textarea
   id: repro-steps
   validations:
    required: true
   attributes:
     label: Steps to reproduce
     description: If so, please provide custom XAML or steps to reproduce. If not, let us know why it can't be reproduced (e.g. more complex setup, environment, dependencies, etc...)
     placeholder: |
1. Given the following environment (Sample App w/ XAML, Project with Isolated setup, etc...)
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

Provide as many code-snippets or XAML snippets as appropriate.
 - type: textarea
   id: expected-behavior
   validations:
    required: true
   attributes:
     label: Expected behavior
     description: A clear and concise description of what you expected to happen.
 - type: markdown
   id: screenshots
   attributes:
     label: Screenshots
     description: If applicable, add screenshots to help explain your problem.
 - type: dropdown
   id: environment-windows-build
   attributes: 
     label: Windows 10 Build Number
     description: Check one or more of the following options
     options:
       - Fall Creators Update (16299)
       - April 2018 Update (17134)
       - October 2018 Update (17763)
       - May 2019 Update (18362)
       - May 2020 Update (19041)
       - Insider Build
 - type: input
   id: insider-build-number-windows
   attributes:
     description: The Insider Builder number, if applicable. 
 - type: dropdown
   id: environment-app-min-target-version
   attributes:
     multiple: true
     label: Windows 10 Build Number
     description: Check one or more of the following options
     options:
       - Fall Creators Update (16299)
       - April 2018 Update (17134)
       - October 2018 Update (17763)
       - May 2019 Update (18362)
       - May 2020 Update (19041)
       - Insider Build
 - type: input
   id: insider-build-number-app
   attributes:
     description: The Insider Builder number, if applicable. 
 - type: dropdown
   id: form-factor
   attributes: 
     multiple: true
     label: Device form factor
     description: Check one or more of the following options
     options:
       - Desktop
       - Xbox
       - Surface Hub
       - IoT
 - type: dropdown
   id: visual-studio-version
   attributes: 
     multiple: true
     label: Device form factor
     description: Check one or more of the following options
     options:
       - 2017
       - 2019
       - 2022
 - type: input
   id: visual-studio-exact-build
   attributes:
     description: What's the exact build number? (Found in Visual Studio under Help -> About Microsoft Visual Studio)
 - type: textarea
   id: nuget-packaages
   attributes:
     description: Which NuGet packages have you used? Include the version number.
 - type: markdown
   id: additional-context
   attributes:
     description: Add any other context about the problem here.
     